# Generated by Django 4.0.6 on 2022-07-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_full_name_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
