# Generated by Django 4.0.6 on 2022-07-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_course_price_student_user_name_teacher_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
