# Generated by Django 4.0.6 on 2022-07-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user_name',
        ),
    ]
