# Generated by Django 4.0.6 on 2022-07-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_student_user_name_remove_teacher_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Instructor',
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name_plural': '1. Instructor'},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='teacher',
            new_name='instructor',
        ),
    ]
