# Generated by Django 4.0.6 on 2022-08-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_course_category_remove_course_techs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.TextField(null=True),
        ),
    ]
