# Generated by Django 4.0.6 on 2022-08-09 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_courserating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name_plural': '6. Course Rating'},
        ),
        migrations.AlterModelOptions(
            name='studentcourseenrollment',
            options={'verbose_name_plural': '5. Enrolled Courses'},
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='instrutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.instructor'),
        ),
    ]
