# Generated by Django 4.0.6 on 2022-08-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_courserating_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourseenrollment',
            old_name='instrutor',
            new_name='instructor',
        ),
    ]
