# Generated by Django 4.0.6 on 2022-08-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_instrutor_studentcourseenrollment_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourseenrollment',
            name='instructor',
        ),
    ]
