# Generated by Django 4.0.6 on 2022-08-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_quiz_quizqustions_coursequiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name_plural': '03. Course Chapter'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '02. Courses'},
        ),
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name_plural': '06. Course Rating'},
        ),
        migrations.AlterModelOptions(
            name='favouritecourse',
            options={'verbose_name_plural': '07. Student Favourite Courses'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name_plural': '01. Instructor'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': '08. Quiz'},
        ),
        migrations.AlterModelOptions(
            name='quizqustions',
            options={'verbose_name_plural': '09. Quiz Questions'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '04. Students'},
        ),
        migrations.AlterModelOptions(
            name='studentcourseenrollment',
            options={'verbose_name_plural': '05. Enrolled Courses'},
        ),
        migrations.AddField(
            model_name='quizqustions',
            name='question',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
