# Generated by Django 4.0.6 on 2022-08-23 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_coursequiz_instructor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursequiz',
            options={'verbose_name_plural': '11. Attempted Questions'},
        ),
        migrations.RemoveField(
            model_name='coursequiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursequiz',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='coursequiz',
            name='quiz',
        ),
        migrations.AddField(
            model_name='coursequiz',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.quizqustions'),
        ),
        migrations.AddField(
            model_name='coursequiz',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
