# Generated by Django 4.0.6 on 2022-08-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_attemptquiz_right_ans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attemptquiz',
            old_name='right_ans',
            new_name='given_ans',
        ),
    ]
