# Generated by Django 4.0.6 on 2022-08-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_reply_options_remove_post_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='add_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quizqustions',
            name='add_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
