# Generated by Django 4.0.6 on 2022-08-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_post_time_alter_quiz_add_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': '14. FAQ',
            },
        ),
    ]
