# Generated by Django 4.0.6 on 2022-08-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='uniq_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='uniq_id',
            field=models.IntegerField(null=True),
        ),
    ]
